# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/mocapviewer.ui'
#
# Created: Wed Jun 18 22:01:36 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MOCAPViewer(object):
    def setupUi(self, MOCAPViewer):
        MOCAPViewer.setObjectName("MOCAPViewer")
        MOCAPViewer.resize(907, 596)
        self.gridLayout = QtGui.QGridLayout(MOCAPViewer)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtGui.QGroupBox(MOCAPViewer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.zincWidget = ZincWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zincWidget.sizePolicy().hasHeightForWidth())
        self.zincWidget.setSizePolicy(sizePolicy)
        self.zincWidget.setObjectName("zincWidget")
        self.verticalLayout.addWidget(self.zincWidget)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 2)
        self.groupBox = QtGui.QGroupBox(MOCAPViewer)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtGui.QListWidget(self.groupBox)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.pushButtonDone = QtGui.QPushButton(MOCAPViewer)
        self.pushButtonDone.setObjectName("pushButtonDone")
        self.verticalLayout_3.addWidget(self.pushButtonDone)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 2, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(MOCAPViewer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelSlider = QtGui.QLabel(self.groupBox_4)
        self.labelSlider.setToolTip("")
        self.labelSlider.setObjectName("labelSlider")
        self.horizontalLayout.addWidget(self.labelSlider)
        self.horizontalSlider = QtGui.QSlider(self.groupBox_4)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.pushButtonPlay = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonPlay.setObjectName("pushButtonPlay")
        self.horizontalLayout.addWidget(self.pushButtonPlay)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(MOCAPViewer)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinBox = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)

        self.retranslateUi(MOCAPViewer)
        QtCore.QMetaObject.connectSlotsByName(MOCAPViewer)

    def retranslateUi(self, MOCAPViewer):
        MOCAPViewer.setWindowTitle(QtGui.QApplication.translate("MOCAPViewer", "MOCAP Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MOCAPViewer", "Labels", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDone.setText(QtGui.QApplication.translate("MOCAPViewer", "&Done", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSlider.setText(QtGui.QApplication.translate("MOCAPViewer", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPlay.setText(QtGui.QApplication.translate("MOCAPViewer", "&Play", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MOCAPViewer", "Icon size:", None, QtGui.QApplication.UnicodeUTF8))

from mapclientplugins.mocapdataviewerstep.zincwidget import ZincWidget
